import 'package:app/generated/json/base/json_convert_content.dart';
import 'package:app/generated/json/base/json_filed.dart';

class SplashEntityEntity with JsonConvert<SplashEntityEntity> {
  int code;
  String message;
  List<SplashEntityResult> result;
}

class SplashEntityResult with JsonConvert<SplashEntityResult> {
  String country;
  @JSONField(name: "piao_id")
  String piaoId;
  @JSONField(name: "res_encryption_flag")
  String resEncryptionFlag;
  @JSONField(name: "mv_provider")
  String mvProvider;
  String biaoshi;
  @JSONField(name: "artist_name")
  String artistName;
  @JSONField(name: "is_first_publish")
  int isFirstPublish;
  String language;
  @JSONField(name: "album_1000_1000")
  String album10001000;
  @JSONField(name: "korean_bb_song")
  String koreanBbSong;
  @JSONField(name: "pic_huge")
  String picHuge;
  @JSONField(name: "all_rate")
  String allRate;
  @JSONField(name: "song_source")
  String songSource;
  @JSONField(name: "song_id")
  String songId;
  @JSONField(name: "album_500_500")
  String album500500;
  String rank;
  @JSONField(name: "pic_premium")
  String picPremium;
  @JSONField(name: "album_800_800")
  String album800800;
  String info;
  String area;
  @JSONField(name: "si_proxycompany")
  String siProxycompany;
  @JSONField(name: "has_mv_mobile")
  int hasMvMobile;
  @JSONField(name: "is_new")
  String isNew;
  String author;
  @JSONField(name: "resource_type")
  String resourceType;
  @JSONField(name: "has_filmtv")
  String hasFilmtv;
  @JSONField(name: "all_artist_ting_uid")
  String allArtistTingUid;
  @JSONField(name: "artist_id")
  String artistId;
  String versions;
  String publishtime;
  String style;
  @JSONField(name: "album_id")
  String albumId;
  @JSONField(name: "album_no")
  String albumNo;
  @JSONField(name: "resource_type_ext")
  String resourceTypeExt;
  @JSONField(name: "del_status")
  String delStatus;
  String hot;
  String toneid;
  String title;
  @JSONField(name: "pic_big")
  String picBig;
  @JSONField(name: "relate_status")
  String relateStatus;
  @JSONField(name: "rank_change")
  String rankChange;
  String lrclink;
  @JSONField(name: "file_duration")
  int fileDuration;
  int havehigh;
  int charge;
  @JSONField(name: "pic_radio")
  String picRadio;
  int learn;
  @JSONField(name: "pic_s500")
  String picS500;
  @JSONField(name: "all_artist_id")
  String allArtistId;
  @JSONField(name: "pic_small")
  String picSmall;
  @JSONField(name: "bitrate_fee")
  String bitrateFee;
  @JSONField(name: "has_mv")
  int hasMv;
  @JSONField(name: "copy_type")
  String copyType;
  @JSONField(name: "ting_uid")
  String tingUid;
  @JSONField(name: "album_title")
  String albumTitle;
}
